
			QueryExec('update hem set hem.atividadeimobiliaria = 1 where hem.emp_codigo = ''0003'' and hem.data = ''2008-07-01'' );
		  
			  QueryExec('insert into hem ( EMP_CODIGO, DATA, OBRIGESCCONTABIL, ENTIDADEFINANC, TRIBUTACAO, OBRIGLUCROREAL, CSLIRPJESTMENSAL, APURACAOIPI, ACRESCPERCENTNORMAL, PISCOFINSCUMULATIVO, IPICENTRALIZADO, PISCOFINSALIQESP'+
						'ECIFICAS, PISCOFINSAPURACAOMISTA, APURARETENCOESPAGAMENTO, APURARPISCOFINSBASEITENS, ATIVIDADEIMOBILIARIA, CONTROLARETENCAORECOLHER, REGIMEAPURACAORECEITA, PLANODECONTASREFERENCIAL, SOCIOOSTENSIVO, AVALIA'+
						'CAOESTOQUEFINAL, ENTIDADESEMFINSLUCRATIVOS, IMUNEOUISENTA, TIPODEENTIDADE, ATIVIDADETRIBUTADAPELOIR, APURACSLL, PRIOAPROCREDITOPISCOFINS, AUTOCREDITOANTPISCOFINS, PISPASEPSOBREFOLHA, APURARETENCOESIRPJPAG'+
						'AMENTO, CLASSIFICACAOTRIBUTARIA, INDICATIVOESCRITURACAO, INDICATIVODESONERACAO, TIPOCPRB, CNAE2_CODIGO, NOMECONTATOREINF, CPFCONTATOREINF, FONEFIXOCONTATOREINF, FONECELULARCONTATOREINF, EMAILCONTATOREINF,'+
						' INDICATIVOSITUACAOPJ, ARREDONDAMENTO, ARREDPROVDESC, ARREDMENORCEDULAVALOR, ARREDFOLHAADIANTARRED, ARREDFOLHAARRED, ARREDFOLHACOMPENS, ARREDFOLHACOMPLARRED, ARREDFOLHACOMPLCOMPENS, ARREDFERIASARRED, ARRE'+
						'DFERIASCOMPENS, ARREDFERIASCOMPLARRED, ARREDFERIASCOMPLCOMPENS, ARRED13SALADIANTARRED, ARRED13SALARRED, ARRED13SALCOMPENS, ARRED13SALCOMPLARRED, ARRED13SALCOMPLCOMPENS, ADIANTAMENTOARREDMODO, INFORMARDIAS'+
						'AUXDOENCA, QTDDIASAUXILIODOENCA, CONTRIBPATRFATURAMENTO, TB_NAT_JUR_CODIGO, COOPERATIVA, CONSTRUTORA, PONTOELETRONICO, ENTIDADEEDUCATIVA, EMPTRABTEMPORARIO, REGEMPTRABTEMPORARIO, ISENCAOMINLEI, ISENCAONUM'+
						'CERT, ISENCAODATAEMISSAO, ISENCAODATAVENCIMENTO, ISENCAONUMPROTREN, ISENCAODATARENOVACAO, ISENCAODATADOU, ISENCAOPAGINADOU, NOMECONTATOESOCIAL, CPFCONTATOESOCIAL, EMAILCONTATOESOCIAL, NUMEROSIAFI, ENTEFED'+
						'ERATIVO, CNPJENTEFEDERATIVO, NOMEENTEFEDERATIVO, UFENTEFEDERATIVO, MUNENTEFEDERATIVO, REGIMEENTEFEDERATIVO, PODERSUBTETOENTEFEDERATIVO, VALORSUBTETOENTEFEDERATIVO, ACORDOINTERNACIONAL, INDICATIVOSITUACAOP'+
						'F, DDDFONEFIXOCONTATOESOCIAL, FONEFIXOCONTATOESOCIAL, DDDCELULARCONTATOESOCIAL, FONECELULARCONTATOESOCIAL ) values ( ''0003'',''2013-06-01'',0,0,3,0,0,0,0,1,0,0,0,0,0,0,0,1,null,0,null,0,null,null,0,0,0,0'+
						',0,0,null,null,null,null,null,null,null,null,null,null,null,''N'',''N'',0,''N'',''N'',''N'',''N'',''N'',''N'',''N'',''N'',''N'',''N'',''N'',''N'',''N'',''N'',null,0,0,0,null,0,0,null,0,0,null,null,null,nu'+
						'll,null,null,null,null,null,null,''           '',null,null,0,null,null,null,null,0,null,null,0,null,null,null,null,null ) ');

			var
			  Query: OleVariant;

			  Query := QueryOpen('select Codigo from EST where EMP_Codigo = ''0003''');
				while not Query.Eof do
				begin
				  QueryExec('insert into HES (EMP_CODIGO, EST_CODIGO, DATA, INFITENSDOCS) values (''0003'',''' + Query.FieldByName('Codigo').Value + ''',''2013-06-01'', 1)');
				  Query.Next;
				end;

			QueryExec('delete from hem where hem.emp_codigo = ''0003'' and hem.data = ''2013-06-01'' ');
			QueryExec('delete from hes where hes.emp_codigo = ''0003'' and hes.data = ''2013-06-01'' ');

