@echo off
chcp 65001 >null

set username=sysdba
set password=masterkey
set /p database=Informe o banco de dados de controle: 
set output1=.\DB_Controle.CSV
set config=.\config.sql

if exist %output1% (del %output1%)
(
    ::comando para configurar o formato de exportação como CSV:
	echo output %output1% format csv delimiter ';';
	
	::comando para selecionar os dados da tabela desejada:
    echo SELECT EMP_CODIGO DSS_EMP_CODIGO, EST_CODIGO, DTEMISSAO, ESPECIE, FORMCONT, NRINICIAL, NRFINAL, CANCELADO, VRTOTAL, PAR_CODIGO, ISSRETIDO, TFRECTRIBCOFINS, TFRECTRIBPIS, TFRECTRIBCSL1, TFRECTRIBCSL2,
    echo        TFRECTRIBIRPJ1, TFRECTRIBIRPJ2, TFRECTRIBIRPJ3, TFRECTRIBIRPJ4, TFRETFONTECOFINS, TFRETFONTEPIS, TFRETFONTECSL, TFRETFONTEIRPJ, TFRETFONTEINSS, GRUPO, GRPVRUTILCONTAB, AMI_SEQ,
	echo        TFRETFONTEIRRF, SDE_CODIGO, FATURA, SERIE, CHAVEELET, OBS, DTPRESTACAO, FDF_SEQ, PAGADORSUS, VRDEDUCOES, VRDESCONTO, VRBRUTO, CCO_CODIGO, INDOBRACONSTRUCAOCIVIL, CNO, PENDENTE,
	echo        OUTRASRETENCOES
	echo FROM DSS
    echo ORDER BY EMP_CODIGO, EST_CODIGO, DTEMISSAO, ESPECIE, CANCELADO, NRINICIAL;

    echo SELECT EMP_CODIGO ITS_EMP_CODIGO, SUBTOTAL, EST_CODIGO, ISSTRIBUTACAO, SERVICOS, ALIQUOTA, MUN_UFD_SIGLA, MUN_CODIGO, NATUREZASERV, ATV_CODIGO, SVS_CODIGO, CSTCOFINS, CSTPIS,
    echo        TFBASECALCCOFINS, TFBASECALCPIS, CODOBRACONSTRCIVIL, NAR_SEQCOFINS, NAR_SEQPIS, VRDEDUCOES, VRDESCONTO, VRBRUTO, PERCENTUALREDUCAO, CCO_CODIGO, TFBCRETFONTEINSS,
    echo        ALIQINSS, VRRETFONTEINSS, VRRETSUBCONTRATACAO, TFBCRETFONTEINSSSERV15, ALIQINSS15, VRSERVICO15, TFBCRETFONTEINSSSERV20, ALIQINSS20, VRSERVICO20, TFBCRETFONTEINSSSERV25,
    echo        ALIQINSS25, VRSERVICO25, VRADICIONALINSS, VRNAORETPROCESSOPRINCIPAL, VRNAORETPROCESSOADICIONAL, EXCLUSAOBCPISCOFINS, TFRECTRIBCOFINSITEM, TFRECTRIBPISITEM
    echo FROM ITS
    echo ORDER BY EMP_CODIGO, EST_CODIGO, DSS_SEQ, SEQ;

    echo SELECT EMP_CODIGO ESI_EMP_CODIGO, EST_CODIGO, PAR_CODIGO, DTEMISSAO, NF, ESPECIE, FORMCONT, NUMERO, VRTOTAL, DTRETENCAO, GRUPO, GRPVRUTILCONTAB, TFRETFONTECOFINS, TFRETFONTEPIS,
    echo        TFRETFONTECSL, TFRETFONTEIRRF, TFRETFONTEINSS, SDE_CODIGO, FATURA, SERIE, CHAVEELET, OBS, TFCREDCOFINSPIS, VRDEDUCOES, VRDESCONTO, VRBRUTO,
    echo        CCO_CODIGO, INDOBRACONSTRUCAOCIVIL, CNO, PENDENTE, OUTRASRETENCOES, DTPRESTACAO
    echo FROM ESI
    echo ORDER BY EMP_CODIGO, EST_CODIGO, ESPECIE, DTEMISSAO, NUMERO;

    echo SELECT EMP_CODIGO IES_EMP_CODIGO, SUBTOTAL, CONSTRUCAOCIVIL, TRIBUTACAO, SERVICOS, ALIQUOTA, GIS_CODIGO, SIO_CODIGO, SVS_CODIGO, CSTPISCOFINS, TFBASECALCPISCOFINS,
    echo        NATBCCRED, CODOBRACONSTRCIVIL, CNAE, VRDEDUCOES, VRDESCONTO, VRBRUTO, CCO_CODIGO, TFBCRETFONTEINSS, ALIQINSS, VRRETFONTEINSS, VRRETSUBCONTRATACAO,
    echo        TFBCRETFONTEINSSSERV15, ALIQINSS15, VRSERVICO15, TFBCRETFONTEINSSSERV20, ALIQINSS20, VRSERVICO20, TFBCRETFONTEINSSSERV25, ALIQINSS25, VRSERVICO25,
    echo        VRADICIONALINSS, VRNAORETPROCESSOPRINCIPAL, VRNAORETPROCESSOADICIONAL, EXCLUSAOBCPISCOFINS, TFRECTRIBCOFINSITEM, TFRECTRIBPISITEM, CBL_CODIGO
    echo FROM IES
    echo ORDER BY EMP_CODIGO, SEQ;
	
    echo SELECT NOME PAR_NOME, UFD_SIGLA, CNPJCPF, IE, IM, INFISSDIGITAL, FORNPRODPRIM, SOCIEDSIMPLES, ENDLOGRADTIPO, ENLOGRADOURO, ENDNUMERO, ENDCOMPLEMENTO, BAIRROTIPO, BAIRRO, CEP,
    echo        MUN_CODIGO, DDD, FONE, SUFRAMA, CFO_CODIGOENTULTUTIL, CFO_CODIGOSAIULTUTIL, ULTICMSALIQENTUTIL, ULTICMSALIQSAIUTIL, SUBSTITUTOISS, ULTCONSTRUCAOCIVIL,
    echo        ORGAOPUBLICO, INDUSTRIA, OPTSIMPLESNAC, PASSAPORTE, PAI_CODIGO, EXTERIOR, ADM_CARTAOCREDITO, EMAIL, HOSPITALEAFINS, INDICADORIE, CNAE21_CODIGO, CPRB,
    echo        PRODUTORRURAL, INDICATIVODAAQUISICAO
    echo FROM PAR
    echo ORDER BY UFD_SIGLA, CNPJCPF, IE, IM;
	
	echo SELECT EMP_CODIGO IFC_EMP_CODIGO, ORIGEM, COMENTARIO, ARQUIVO, EXCLUIDO, DTINICIAL, DTFINAL, CONTEXTO, PISCOFINSALIQUOTAESPECIFICA, NOTASFISCAISDECLARADASAM, VERSAOARQUIVO,
	echo        PENDENTECANCELAMENTO, PENDENTEIMPORTACAO
	echo FROM IFC
	echo ORDER BY EMP_CODIGO, ORIGEM, ARQUIVO, VERSAOARQUIVO, DTINICIAL;
) > %config%

call "C:\Program Files\Firebird\Firebird_2_5\bin\isql" -user %username% -password %password% %database% -i %config% -o %output1%

::
:: SEGUNDO ARQUIVO
::

set /p database=Informe o banco de dados de homologacao: 
set output2=.\DB_Homologacao.CSV

if exist %output2% (del %output2%)
(
    ::comando para configurar o formato de exportação como CSV:
	echo output %output2% format csv delimiter ';';
	
	::comando para selecionar os dados da tabela desejada:
    echo SELECT EMP_CODIGO DSS_EMP_CODIGO, EST_CODIGO, DTEMISSAO, ESPECIE, FORMCONT, NRINICIAL, NRFINAL, CANCELADO, VRTOTAL, PAR_CODIGO, ISSRETIDO, TFRECTRIBCOFINS, TFRECTRIBPIS, TFRECTRIBCSL1, TFRECTRIBCSL2,
    echo        TFRECTRIBIRPJ1, TFRECTRIBIRPJ2, TFRECTRIBIRPJ3, TFRECTRIBIRPJ4, TFRETFONTECOFINS, TFRETFONTEPIS, TFRETFONTECSL, TFRETFONTEIRPJ, TFRETFONTEINSS, GRUPO, GRPVRUTILCONTAB, AMI_SEQ,
	echo        TFRETFONTEIRRF, SDE_CODIGO, FATURA, SERIE, CHAVEELET, OBS, DTPRESTACAO, FDF_SEQ, PAGADORSUS, VRDEDUCOES, VRDESCONTO, VRBRUTO, CCO_CODIGO, INDOBRACONSTRUCAOCIVIL, CNO, PENDENTE,
	echo        OUTRASRETENCOES
	echo FROM DSS
    echo ORDER BY EMP_CODIGO, EST_CODIGO, DTEMISSAO, ESPECIE, CANCELADO, NRINICIAL;

    echo SELECT EMP_CODIGO ITS_EMP_CODIGO, SUBTOTAL, EST_CODIGO, ISSTRIBUTACAO, SERVICOS, ALIQUOTA, MUN_UFD_SIGLA, MUN_CODIGO, NATUREZASERV, ATV_CODIGO, SVS_CODIGO, CSTCOFINS, CSTPIS,
    echo        TFBASECALCCOFINS, TFBASECALCPIS, CODOBRACONSTRCIVIL, NAR_SEQCOFINS, NAR_SEQPIS, VRDEDUCOES, VRDESCONTO, VRBRUTO, PERCENTUALREDUCAO, CCO_CODIGO, TFBCRETFONTEINSS,
    echo        ALIQINSS, VRRETFONTEINSS, VRRETSUBCONTRATACAO, TFBCRETFONTEINSSSERV15, ALIQINSS15, VRSERVICO15, TFBCRETFONTEINSSSERV20, ALIQINSS20, VRSERVICO20, TFBCRETFONTEINSSSERV25,
    echo        ALIQINSS25, VRSERVICO25, VRADICIONALINSS, VRNAORETPROCESSOPRINCIPAL, VRNAORETPROCESSOADICIONAL, EXCLUSAOBCPISCOFINS, TFRECTRIBCOFINSITEM, TFRECTRIBPISITEM
    echo FROM ITS
    echo ORDER BY EMP_CODIGO, EST_CODIGO, DSS_SEQ, SEQ;

    echo SELECT EMP_CODIGO ESI_EMP_CODIGO, EST_CODIGO, PAR_CODIGO, DTEMISSAO, NF, ESPECIE, FORMCONT, NUMERO, VRTOTAL, DTRETENCAO, GRUPO, GRPVRUTILCONTAB, TFRETFONTECOFINS, TFRETFONTEPIS,
    echo        TFRETFONTECSL, TFRETFONTEIRRF, TFRETFONTEINSS, SDE_CODIGO, FATURA, SERIE, CHAVEELET, OBS, TFCREDCOFINSPIS, VRDEDUCOES, VRDESCONTO, VRBRUTO,
    echo        CCO_CODIGO, INDOBRACONSTRUCAOCIVIL, CNO, PENDENTE, OUTRASRETENCOES, DTPRESTACAO
    echo FROM ESI
    echo ORDER BY EMP_CODIGO, EST_CODIGO, ESPECIE, DTEMISSAO, NUMERO;

    echo SELECT EMP_CODIGO IES_EMP_CODIGO, SUBTOTAL, CONSTRUCAOCIVIL, TRIBUTACAO, SERVICOS, ALIQUOTA, GIS_CODIGO, SIO_CODIGO, SVS_CODIGO, CSTPISCOFINS, TFBASECALCPISCOFINS,
    echo        NATBCCRED, CODOBRACONSTRCIVIL, CNAE, VRDEDUCOES, VRDESCONTO, VRBRUTO, CCO_CODIGO, TFBCRETFONTEINSS, ALIQINSS, VRRETFONTEINSS, VRRETSUBCONTRATACAO,
    echo        TFBCRETFONTEINSSSERV15, ALIQINSS15, VRSERVICO15, TFBCRETFONTEINSSSERV20, ALIQINSS20, VRSERVICO20, TFBCRETFONTEINSSSERV25, ALIQINSS25, VRSERVICO25,
    echo        VRADICIONALINSS, VRNAORETPROCESSOPRINCIPAL, VRNAORETPROCESSOADICIONAL, EXCLUSAOBCPISCOFINS, TFRECTRIBCOFINSITEM, TFRECTRIBPISITEM, CBL_CODIGO
    echo FROM IES
    echo ORDER BY EMP_CODIGO, SEQ;
	
    echo SELECT NOME PAR_NOME, UFD_SIGLA, CNPJCPF, IE, IM, INFISSDIGITAL, FORNPRODPRIM, SOCIEDSIMPLES, ENDLOGRADTIPO, ENLOGRADOURO, ENDNUMERO, ENDCOMPLEMENTO, BAIRROTIPO, BAIRRO, CEP,
    echo        MUN_CODIGO, DDD, FONE, SUFRAMA, CFO_CODIGOENTULTUTIL, CFO_CODIGOSAIULTUTIL, ULTICMSALIQENTUTIL, ULTICMSALIQSAIUTIL, SUBSTITUTOISS, ULTCONSTRUCAOCIVIL,
    echo        ORGAOPUBLICO, INDUSTRIA, OPTSIMPLESNAC, PASSAPORTE, PAI_CODIGO, EXTERIOR, ADM_CARTAOCREDITO, EMAIL, HOSPITALEAFINS, INDICADORIE, CNAE21_CODIGO, CPRB,
    echo        PRODUTORRURAL, INDICATIVODAAQUISICAO
    echo FROM PAR
    echo ORDER BY UFD_SIGLA, CNPJCPF, IE, IM;
	
	echo SELECT EMP_CODIGO IFC_EMP_CODIGO, ORIGEM, COMENTARIO, ARQUIVO, EXCLUIDO, DTINICIAL, DTFINAL, CONTEXTO, PISCOFINSALIQUOTAESPECIFICA, NOTASFISCAISDECLARADASAM, VERSAOARQUIVO,
	echo        PENDENTECANCELAMENTO, PENDENTEIMPORTACAO
	echo FROM IFC
	echo ORDER BY EMP_CODIGO, ORIGEM, ARQUIVO, VERSAOARQUIVO, DTINICIAL;
) > %config%

call "C:\Program Files\Firebird\Firebird_2_5\bin\isql" -user %username% -password %password% %database% -i %config% -o %output2%
del %config%
del null
kdiff3 %output1% %output2%