@echo off
chcp 65001 >null

set username=sysdba
set password=masterkey
set /p database=Informe o banco de dados de controle: 
set output1=.\DB_Controle.CSV
set config=.\config.sql

if exist %output1% (del %output1%)
(
    ::comando para configurar o formato de exportação como CSV:
	echo output %output1% format csv delimiter ';';
	
	::comando para selecionar os dados da tabela desejada:
    echo SELECT EMP_CODIGO NFM_EMP_CODIGO, SEQ, EST_CODIGO, OPERACAO, ESPECIE, DOCPROPRIO, DAI_AID_SEQ, DAI_SEQ, SERIE, SUBSERIE, NUMERO, FORMULINICIAL, FORMULFINAL, DTEMISSAO, CANCELADO,
	echo        DTENTRADASAIDA, DTDOC, PAR_CODIGO, GNREVINCULADA, GNREICMS, GNREANOMES, GNRECONVENIO, GNREDTVENC, GNREDTRECOLHIM, GNREBANCO, GNREAGENCIA, GNREAGENCIADV, GNREAUTENTIC,
	echo        TOTALPRODUTOS, TOTALFRETE, TOTALSEGURO, TOTALOUTRASDESP, TOTALICMSIMPORT, TOTALICMSIMPDIF, TOTALIPIVR, TOTALSUBSTRET, TOTALSERVISS, TOTALDESCGLOBAL, TOTALVR, QTDITENSPROD,
	echo        ARECSUBST, ARECANTEC, ARECDIFALIQ, SUBSTVRCONTABIL, SUBSTBASECALC, ANTECVRCONTABIL, ISSRETIDO, DTRETENCAO, DTENTRADAESTADO, FRETEPORCONTA, FATURA, EEC_NUMERO, NUMEROCF,
	echo        CCO_CODIGO, TFRECTRIBCOFINS, TFRECTRIBPIS, TFRECTRIBCSL1, TFRECTRIBCSL2, TFRECTRIBIRPJ1, TFRECTRIBIRPJ2, TFRECTRIBIRPJ3, TFRECTRIBIRPJ4, TFRETFONTECOFINS, TFRETFONTEPIS,
	echo        TFRETFONTECSL, TFRETFONTEIRPJ, GRUPO, GRPVRUTILCONTAB, NOTACOMP, NUMEROPAG, DATAPAG, TIPOPAG, SDE_CODIGO, NFVENDAFORAESTAB, ALIQSUBST, TFCREDCOFINSPIS, CHAVEELET,
	echo        TFRETFONTEINSS, PENDENTE, OBS, STATUSENVIO, RETORNOENVIO, MOTIVOCANC, PROTOCOLONFE, AMBIENTEDIGITACAO, NOP_CODIGO, CDF_CODIGO, CDFCOMPLEMENTO, HORA_ENTRADASAIDA,
	echo        UFD_SIGLA_EMBARQ, LOCALEMBARQ, FDF_SEQ, PISCOFINSALIQUOTAESPECIFICA, REFNFE, INFADFISCO, SPDDATAENVIO, SPDICODIGO, SPDMSG, DTCONTINGENCIA, HORACONTINGENCIA, OPERACAOCONSUMIDORFINAL,
	echo        PRESENCACOMPRADOR, NOTADIGITADAPELOCONTRIBUINTE, NOTADECLARADAAM, IFC_SEQ_NOTASDEC_AM, TOTALICMSDESONERACAO, INDOBRACONSTRUCAOCIVIL, CNO, DTESCRITURACAO, TOTALFCP,
	echo        EHNFESAIDATERCEIROS, TOTALICMSMONORET, DECRETO353952023CE
	echo FROM NFM
    echo ORDER BY EMP_CODIGO, EST_CODIGO, DTDOC, ESPECIE, CANCELADO, SERIE, SUBSERIE, NUMERO;

    echo SELECT EMP_CODIGO INM_EMP_CODIGO, NFM_SEQ, SEQ, UFD_SIGLA, CFO_CODIGO, VALOR, ICMSBASECALC, ICMSALIQ, ICMSDEBCRED, ICMSISENTAS, ICMSOUTRAS, IPIBASECALC, IPIDEBCRED, IPIISENTAS,
	echo        IPIOUTRAS, PERCREDUC, SUBSTICMS, SUBSTIPI, SUBSTCOFINS, SUBSTPIS, PERCICMSSUBST, CALCFECOPDEC29560, CSOSNA, CSOSNB, CSTIPI, CSTA, CSTB, COFINSMONO, PISMONO, FCPBASECALC,
	echo        FCPALIQUOTA, FCPVALOR, FCPBASECALCSUBS, FCPALIQUOTASUBS, FCPVALORSUBS, ALIQ_ICMS_DIFERIMENTO
    echo FROM INM
    echo ORDER BY EMP_CODIGO, NFM_SEQ, SEQ;

    echo SELECT EMP_CODIGO ITM_EMP_CODIGO, PNM_NFM_SEQ, PNM_SEQ, SEQ, NUMLOTE, QTDITENSLOTE, DTFABRICACAO, DTVALIDADE, INDICADORBCMEDICAMENTO, VLMAXIMOTABELADO
    echo FROM ITM
    echo ORDER BY EMP_CODIGO, PNM_NFM_SEQ, PNM_SEQ, SEQ, NUMLOTE;

    echo SELECT EMP_CODIGO PNM_EMP_CODIGO, NFM_SEQ, SEQ, PRO_CODIGO, CFO_CODIGO, CSTA, CSTB, UNIDMEDIDA, QUANTIDADE, VRTOTAL, IPIVR, ICMSTRIBUTACAO, ICMSBASECALC, ICMSALIQ, ICMSSUBSTBC,
	echo        ICMSSUBSTVR, ARECOLHER, SUBSTTIPO, SUBSTCUSTOAQ, SUBSTAGREG, SUBSTBASECALC, SUBSTALIQ, SUBSTCREDORIG, SUBSTJAREC, ANTECCUSTOAQ, ANTECAGREG, ANTECALIQ, ANTECCREDORIG, ANTECJAREC,
	echo        DIFALIQBASECALC, DIFALIQALIQORIG, DIFALIQALIQINT, IPITRIBUTACAO, IPIBASECALC, IPIALIQ, IPIDEBCRED, CCO_CODIGO, PERCREDANTEC, CSTIPI, CSTCOFINS, CSTPIS, TFBASECALCCOFINS,
	echo        TFBASECALCPIS, PERCICMSSUBST, CALCFECOPDECPNM, RESSARCIMENTO, VRDESCONTO, VRBRUTO, VRFRETE, VRSEGURO, CSOSNA, CSOSNB, NAR_SEQCOFINS, NAR_SEQPIS, PRODEPEINDESP, PRODEPECODAPUR,
	echo        VRUNITARIO, TIPOCALCULOCOFINS, ALIQUOTACOFINSPERC, ALIQUOTACOFINSEMREAIS, VALORCOFINS, TIPOCALCULOPIS, ALIQUOTAPISPERC, ALIQUOTAPISEMREAIS, VALORPIS, CAF_SEQ, PEDIDOCOMPRA,
	echo        ITEMPEDIDOCOMPRA, BASECALCIMPOSTO, DESPADUANEIRAS, VALORIMPOSTO, IMPOSTOIOF, VROUTRASDESPESAS, NAOCOMPOEVALORTOTAL, NATCREDESTORNOPIS, NATCREDESTORNOCOFINS, NATCONTESTORNOPIS,
	echo        NATCONTESTORNOCOFINS, FCI, INDPETROLEO, PERCIPIDEVOLVIDO, MOTIVODEVOLUCAO, RECOPI, INDESPINCENTIVOPRODEP, VRICMSDESONERACAO, MOTIVODESONERACAO, DIFALBCICMS, DIFALALIQFECOP,
	echo        DIFALALIQORIGEM, DIFALALIQDESTINO, DIFALICMSDIFERALIQ, DIFALUFORIGEM, DIFALUFDESTINO, DIFALICMSPARTILHAORIGEM, DIFALICMSPARTILHADESTINO, DIFALICMSORIGEM, DIFALICMSDESTINO,
	echo        DIFALICMSFECOP, EXCLUSAOBCPISCOFINS, DIFALIQALIQEXT, FCPBASECALC, FCPALIQUOTA, FCPVALOR, FCPBASECALCSUBS, FCPALIQUOTASUBS, FCPVALORSUBS, RSTESPECIE, RSTDTDOCUMENTO, RSTNUMERO,
	echo        RSTSERIE, RSTCHAVEELET, RSTPAR_CODIGO, RSTCODIGOITEM, RSTQUANTIDADE, RSTVRUNITARIO, RSTVRBCICMSST, RSTVRUNITBCICMSREMETENTE, RSTALIQICMSREMETENTE, RSTVRUNITBCICMSRETENCAO,
	echo        RSTVRUNITCREDICMS, RSTALIQICMSST, RSTVRUNITBCICMSSTRESS, RSTCODRETENCAOICMSST, RSTCODMOTIVORESS, RSTCHAVEELETEMITSUBST, RSTPAR_CODRETENCAOICMSST, RSTNUMERORETENCAOICMSST,
	echo        RSTRETENCAOICMSSTSERIE, RSTRETOICMSSTCODITEM, RSTCODDOCARRECADACAO, RSTNUMERODOCARRECADACAO, AJUSTEICMSBASECALC, AJUSTEICMSALIQ, AJUSTEICMSVALOR, AJUSTEICMSOUTROS,
	echo        ALIQ_ICMS_DIFERIMENTO, VALORSUBSTITUTOICMS, DECRETO463032018PE, DECRETO2068699AM, ICMSBCMONO, ICMSALIQMONO, ICMSMONO, ICMSBCMONORET, ICMSALIQMONORET, ICMSMONORET, ICMSBCMONODIF,
	echo        ICMSALIQMONODIF, ICMSALIQDIFMONODIF, ICMSMONODIF, ICMSBCMONORETANT, ICMSALIQMONORETANT, ICMSMONORETANT
    echo FROM PNM
    echo ORDER BY EMP_CODIGO, PNM_EMP_CODIGO, NFM_SEQ, SEQ;
	
    echo SELECT NOME PAR_NOME, UFD_SIGLA, CNPJCPF, IE, IM, INFISSDIGITAL, FORNPRODPRIM, SOCIEDSIMPLES, ENDLOGRADTIPO, ENLOGRADOURO, ENDNUMERO, ENDCOMPLEMENTO, BAIRROTIPO, BAIRRO, CEP,
    echo        MUN_CODIGO, DDD, FONE, SUFRAMA, CFO_CODIGOENTULTUTIL, CFO_CODIGOSAIULTUTIL, ULTICMSALIQENTUTIL, ULTICMSALIQSAIUTIL, SUBSTITUTOISS, ULTCONSTRUCAOCIVIL,
    echo        ORGAOPUBLICO, INDUSTRIA, OPTSIMPLESNAC, PASSAPORTE, PAI_CODIGO, EXTERIOR, ADM_CARTAOCREDITO, EMAIL, HOSPITALEAFINS, INDICADORIE, CNAE21_CODIGO, CPRB,
    echo        PRODUTORRURAL, INDICATIVODAAQUISICAO
    echo FROM PAR
    echo ORDER BY UFD_SIGLA, CNPJCPF, IE, IM;
	
	echo SELECT EMP_CODIGO IFC_EMP_CODIGO, ORIGEM, COMENTARIO, ARQUIVO, EXCLUIDO, DTINICIAL, DTFINAL, CONTEXTO, PISCOFINSALIQUOTAESPECIFICA, NOTASFISCAISDECLARADASAM, VERSAOARQUIVO,
	echo        PENDENTECANCELAMENTO, PENDENTEIMPORTACAO
	echo FROM IFC
	echo ORDER BY EMP_CODIGO, ORIGEM, ARQUIVO, VERSAOARQUIVO, DTINICIAL;
) > %config%

call "C:\Program Files\Firebird\Firebird_2_5\bin\isql" -user %username% -password %password% %database% -i %config% -o %output1%

::
:: SEGUNDO ARQUIVO
::

set /p database=Informe o banco de dados de homologacao: 
set output2=.\DB_Homologacao.CSV

if exist %output2% (del %output2%)
(
    ::comando para configurar o formato de exportação como CSV:
	echo output %output2% format csv delimiter ';';
	
	::comando para selecionar os dados da tabela desejada:
    echo SELECT EMP_CODIGO NFM_EMP_CODIGO, SEQ, EST_CODIGO, OPERACAO, ESPECIE, DOCPROPRIO, DAI_AID_SEQ, DAI_SEQ, SERIE, SUBSERIE, NUMERO, FORMULINICIAL, FORMULFINAL, DTEMISSAO, CANCELADO,
	echo        DTENTRADASAIDA, DTDOC, PAR_CODIGO, GNREVINCULADA, GNREICMS, GNREANOMES, GNRECONVENIO, GNREDTVENC, GNREDTRECOLHIM, GNREBANCO, GNREAGENCIA, GNREAGENCIADV, GNREAUTENTIC,
	echo        TOTALPRODUTOS, TOTALFRETE, TOTALSEGURO, TOTALOUTRASDESP, TOTALICMSIMPORT, TOTALICMSIMPDIF, TOTALIPIVR, TOTALSUBSTRET, TOTALSERVISS, TOTALDESCGLOBAL, TOTALVR, QTDITENSPROD,
	echo        ARECSUBST, ARECANTEC, ARECDIFALIQ, SUBSTVRCONTABIL, SUBSTBASECALC, ANTECVRCONTABIL, ISSRETIDO, DTRETENCAO, DTENTRADAESTADO, FRETEPORCONTA, FATURA, EEC_NUMERO, NUMEROCF,
	echo        CCO_CODIGO, TFRECTRIBCOFINS, TFRECTRIBPIS, TFRECTRIBCSL1, TFRECTRIBCSL2, TFRECTRIBIRPJ1, TFRECTRIBIRPJ2, TFRECTRIBIRPJ3, TFRECTRIBIRPJ4, TFRETFONTECOFINS, TFRETFONTEPIS,
	echo        TFRETFONTECSL, TFRETFONTEIRPJ, GRUPO, GRPVRUTILCONTAB, NOTACOMP, NUMEROPAG, DATAPAG, TIPOPAG, SDE_CODIGO, NFVENDAFORAESTAB, ALIQSUBST, TFCREDCOFINSPIS, CHAVEELET,
	echo        TFRETFONTEINSS, PENDENTE, OBS, STATUSENVIO, RETORNOENVIO, MOTIVOCANC, PROTOCOLONFE, AMBIENTEDIGITACAO, NOP_CODIGO, CDF_CODIGO, CDFCOMPLEMENTO, HORA_ENTRADASAIDA,
	echo        UFD_SIGLA_EMBARQ, LOCALEMBARQ, FDF_SEQ, PISCOFINSALIQUOTAESPECIFICA, REFNFE, INFADFISCO, SPDDATAENVIO, SPDICODIGO, SPDMSG, DTCONTINGENCIA, HORACONTINGENCIA, OPERACAOCONSUMIDORFINAL,
	echo        PRESENCACOMPRADOR, NOTADIGITADAPELOCONTRIBUINTE, NOTADECLARADAAM, IFC_SEQ_NOTASDEC_AM, TOTALICMSDESONERACAO, INDOBRACONSTRUCAOCIVIL, CNO, DTESCRITURACAO, TOTALFCP,
	echo        EHNFESAIDATERCEIROS, TOTALICMSMONORET, DECRETO353952023CE
	echo FROM NFM
    echo ORDER BY EMP_CODIGO, EST_CODIGO, DTDOC, ESPECIE, CANCELADO, SERIE, SUBSERIE, NUMERO;

    echo SELECT EMP_CODIGO INM_EMP_CODIGO, NFM_SEQ, SEQ, UFD_SIGLA, CFO_CODIGO, VALOR, ICMSBASECALC, ICMSALIQ, ICMSDEBCRED, ICMSISENTAS, ICMSOUTRAS, IPIBASECALC, IPIDEBCRED, IPIISENTAS,
	echo        IPIOUTRAS, PERCREDUC, SUBSTICMS, SUBSTIPI, SUBSTCOFINS, SUBSTPIS, PERCICMSSUBST, CALCFECOPDEC29560, CSOSNA, CSOSNB, CSTIPI, CSTA, CSTB, COFINSMONO, PISMONO, FCPBASECALC,
	echo        FCPALIQUOTA, FCPVALOR, FCPBASECALCSUBS, FCPALIQUOTASUBS, FCPVALORSUBS, ALIQ_ICMS_DIFERIMENTO
    echo FROM INM
    echo ORDER BY EMP_CODIGO, NFM_SEQ, SEQ;

    echo SELECT EMP_CODIGO ITM_EMP_CODIGO, PNM_NFM_SEQ, PNM_SEQ, SEQ, NUMLOTE, QTDITENSLOTE, DTFABRICACAO, DTVALIDADE, INDICADORBCMEDICAMENTO, VLMAXIMOTABELADO
    echo FROM ITM
    echo ORDER BY EMP_CODIGO, PNM_NFM_SEQ, PNM_SEQ, SEQ, NUMLOTE;

    echo SELECT EMP_CODIGO PNM_EMP_CODIGO, NFM_SEQ, SEQ, PRO_CODIGO, CFO_CODIGO, CSTA, CSTB, UNIDMEDIDA, QUANTIDADE, VRTOTAL, IPIVR, ICMSTRIBUTACAO, ICMSBASECALC, ICMSALIQ, ICMSSUBSTBC,
	echo        ICMSSUBSTVR, ARECOLHER, SUBSTTIPO, SUBSTCUSTOAQ, SUBSTAGREG, SUBSTBASECALC, SUBSTALIQ, SUBSTCREDORIG, SUBSTJAREC, ANTECCUSTOAQ, ANTECAGREG, ANTECALIQ, ANTECCREDORIG, ANTECJAREC,
	echo        DIFALIQBASECALC, DIFALIQALIQORIG, DIFALIQALIQINT, IPITRIBUTACAO, IPIBASECALC, IPIALIQ, IPIDEBCRED, CCO_CODIGO, PERCREDANTEC, CSTIPI, CSTCOFINS, CSTPIS, TFBASECALCCOFINS,
	echo        TFBASECALCPIS, PERCICMSSUBST, CALCFECOPDECPNM, RESSARCIMENTO, VRDESCONTO, VRBRUTO, VRFRETE, VRSEGURO, CSOSNA, CSOSNB, NAR_SEQCOFINS, NAR_SEQPIS, PRODEPEINDESP, PRODEPECODAPUR,
	echo        VRUNITARIO, TIPOCALCULOCOFINS, ALIQUOTACOFINSPERC, ALIQUOTACOFINSEMREAIS, VALORCOFINS, TIPOCALCULOPIS, ALIQUOTAPISPERC, ALIQUOTAPISEMREAIS, VALORPIS, CAF_SEQ, PEDIDOCOMPRA,
	echo        ITEMPEDIDOCOMPRA, BASECALCIMPOSTO, DESPADUANEIRAS, VALORIMPOSTO, IMPOSTOIOF, VROUTRASDESPESAS, NAOCOMPOEVALORTOTAL, NATCREDESTORNOPIS, NATCREDESTORNOCOFINS, NATCONTESTORNOPIS,
	echo        NATCONTESTORNOCOFINS, FCI, INDPETROLEO, PERCIPIDEVOLVIDO, MOTIVODEVOLUCAO, RECOPI, INDESPINCENTIVOPRODEP, VRICMSDESONERACAO, MOTIVODESONERACAO, DIFALBCICMS, DIFALALIQFECOP,
	echo        DIFALALIQORIGEM, DIFALALIQDESTINO, DIFALICMSDIFERALIQ, DIFALUFORIGEM, DIFALUFDESTINO, DIFALICMSPARTILHAORIGEM, DIFALICMSPARTILHADESTINO, DIFALICMSORIGEM, DIFALICMSDESTINO,
	echo        DIFALICMSFECOP, EXCLUSAOBCPISCOFINS, DIFALIQALIQEXT, FCPBASECALC, FCPALIQUOTA, FCPVALOR, FCPBASECALCSUBS, FCPALIQUOTASUBS, FCPVALORSUBS, RSTESPECIE, RSTDTDOCUMENTO, RSTNUMERO,
	echo        RSTSERIE, RSTCHAVEELET, RSTPAR_CODIGO, RSTCODIGOITEM, RSTQUANTIDADE, RSTVRUNITARIO, RSTVRBCICMSST, RSTVRUNITBCICMSREMETENTE, RSTALIQICMSREMETENTE, RSTVRUNITBCICMSRETENCAO,
	echo        RSTVRUNITCREDICMS, RSTALIQICMSST, RSTVRUNITBCICMSSTRESS, RSTCODRETENCAOICMSST, RSTCODMOTIVORESS, RSTCHAVEELETEMITSUBST, RSTPAR_CODRETENCAOICMSST, RSTNUMERORETENCAOICMSST,
	echo        RSTRETENCAOICMSSTSERIE, RSTRETOICMSSTCODITEM, RSTCODDOCARRECADACAO, RSTNUMERODOCARRECADACAO, AJUSTEICMSBASECALC, AJUSTEICMSALIQ, AJUSTEICMSVALOR, AJUSTEICMSOUTROS,
	echo        ALIQ_ICMS_DIFERIMENTO, VALORSUBSTITUTOICMS, DECRETO463032018PE, DECRETO2068699AM, ICMSBCMONO, ICMSALIQMONO, ICMSMONO, ICMSBCMONORET, ICMSALIQMONORET, ICMSMONORET, ICMSBCMONODIF,
	echo        ICMSALIQMONODIF, ICMSALIQDIFMONODIF, ICMSMONODIF, ICMSBCMONORETANT, ICMSALIQMONORETANT, ICMSMONORETANT
    echo FROM PNM
    echo ORDER BY EMP_CODIGO, PNM_EMP_CODIGO, NFM_SEQ, SEQ;
	
    echo SELECT NOME PAR_NOME, UFD_SIGLA, CNPJCPF, IE, IM, INFISSDIGITAL, FORNPRODPRIM, SOCIEDSIMPLES, ENDLOGRADTIPO, ENLOGRADOURO, ENDNUMERO, ENDCOMPLEMENTO, BAIRROTIPO, BAIRRO, CEP,
    echo        MUN_CODIGO, DDD, FONE, SUFRAMA, CFO_CODIGOENTULTUTIL, CFO_CODIGOSAIULTUTIL, ULTICMSALIQENTUTIL, ULTICMSALIQSAIUTIL, SUBSTITUTOISS, ULTCONSTRUCAOCIVIL,
    echo        ORGAOPUBLICO, INDUSTRIA, OPTSIMPLESNAC, PASSAPORTE, PAI_CODIGO, EXTERIOR, ADM_CARTAOCREDITO, EMAIL, HOSPITALEAFINS, INDICADORIE, CNAE21_CODIGO, CPRB,
    echo        PRODUTORRURAL, INDICATIVODAAQUISICAO
    echo FROM PAR
    echo ORDER BY UFD_SIGLA, CNPJCPF, IE, IM;
	
	echo SELECT EMP_CODIGO IFC_EMP_CODIGO, ORIGEM, COMENTARIO, ARQUIVO, EXCLUIDO, DTINICIAL, DTFINAL, CONTEXTO, PISCOFINSALIQUOTAESPECIFICA, NOTASFISCAISDECLARADASAM, VERSAOARQUIVO,
	echo        PENDENTECANCELAMENTO, PENDENTEIMPORTACAO
	echo FROM IFC
	echo ORDER BY EMP_CODIGO, ORIGEM, ARQUIVO, VERSAOARQUIVO, DTINICIAL;
) > %config%

call "C:\Program Files\Firebird\Firebird_2_5\bin\isql" -user %username% -password %password% %database% -i %config% -o %output2%
del %config%
del null
kdiff3 %output1% %output2%