@echo off

Title SIMPLIFICADA / EXTRAORDINARIA
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\AcessoriosFisco\ACF Unitarios Firebird 2.5 versao Simplificada") do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\AcessoriosFisco\ACF Unitarios MSSQL versao Simplificada") do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\AcessoriosFisco\ACT Unitarios Firebird 2.5 versao Simplificada"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\AcessoriosFisco\ACT Unitarios MSSQL versao Simplificada"\*) do rd /s /q "%%i"

Title METRICAS AC
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Metricas\Classes com Muitos M_todos (Sistema\*") do rd /s /q %%i
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Metricas\Duplica__o de C_digo (Sistema)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Metricas\Duplica__o de C_digo (Testes)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Metricas\M_todos com Muitas Linhas (Sistema)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Metricas\M_todos com Muitas Linhas (Testes)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Metricas\M_todos Complexos (Sistema)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Metricas\M_todos Complexos (Testes)"\*) do rd /s /q "%%i"

Title METRICAS PATRIO
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\MTricasPatrio\1.05 M_todos Complexos (Testes)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\MTricasPatrio\1.06 Classes com Muitos M_todos (Sistema)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\MTricasPatrio\1.07 M_todos Complexos (Sistema)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\MTricasPatrio\1.07 M_todos Complexos (Sistema)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\MTricasPatrio\1.09 M_todos com Muitas Linhas (Sistema)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\MTricasPatrio\1.10 M_todos com Muitas Linhas (Testes)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\MTricasPatrio\1.11 Duplica__o de C_digo (Sistema)"\*) do rd /s /q "%%i"

Title PATRIO
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Patrio\1.01 PatrioTestesUnitariosFirebird25"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Patrio\1.02 PatrioTestesUnitariosMSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Patrio\1.03 PatrioTestesFuncionaisFirebird25"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\Patrio\1.04 PatrioTestesFuncionaisSQLServer"\*) do rd /s /q "%%i"

Title GESTAO
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcGestao\1. CO Funcional Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcGestao\2. CO Funcional MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcGestao\CO Unitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcGestao\CO Unitarios MSSQL"\*) do rd /s /q "%%i"

Title GESTAO XE6
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcGestaoXe6\1 CO Unitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcGestaoXe6\1.1 CO Unitarios MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcGestaoXe6\2 CO Funcional Firebird 2.1"\*) do rd /s /q "%%i"

Title CONTABIL
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\1.1 ACT Funcional Cadastros Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\1.2.1 ACT Funcional Movimentos Firebird 2.1 (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\1.2.2 ACT Funcional Movimentos Firebird 2.1 (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\1.3 ACT Funcional Relatorios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\1.4 ACT Funcional Utilitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\2.1 ACT Funcional Cadastros MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\2.2.1 ACT Funcional Movimentos MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\2.2.2 ACT Funcional Movimentos MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\2.3 ACT Funcional Relatorios MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\2.4 ACT Funcional Utilitarios MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\ACT Unitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcContabil\ACT Unitarios MSSQL"\*) do rd /s /q "%%i"

Title CONTABIL XE6
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TesteAcContabilXe6\3.1 ACT Funcional Movimentos Firebird 2.1 (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TesteAcContabilXe6\1.1 ACT Unitarios MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TesteAcContabilXe6\1 ACT Unitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TesteAcContabilXe6\5 ACT Funcional Utilitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TesteAcContabilXe6\4 ACT Funcional Relatorios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TesteAcContabilXe6\2 ACT Funcional Cadastros Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TesteAcContabilXe6\3.2 ACT Funcional Movimentos Firebird 2.1 (Parte2)"\*) do rd /s /q "%%i"

Title FISCAL
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\0.2 ACF Unitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\0.3 ACF Unitarios MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.1.1 ACF Funcional Cadastros MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.1.2 ACF Funcional Cadastros MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.1.3 ACF Funcional Cadastros MSSQL (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.2.1 ACF Funcional Mov. Entradas MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.2.2 ACF Funcional Mov. Entradas MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.2.3 ACF Funcional Mov. Entradas MSSQL (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.3.1 ACF Funcional Mov. Sa_das MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.3.2 ACF Funcional Mov. Sa_das MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.3.3 ACF Funcional Mov. Sa_das MSSQL (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.4.1 ACF Funcional Outros Movimentos MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.4.2 ACF Funcional Outros Movimentos MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.4.3 ACF Funcional Outros Movimentos MSSQL (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.5.1 ACF Funcional Movimentos Geracao MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.5.2 ACF Funcional Movimentos Geracao MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.5.3 ACF Funcional Movimentos Geracao MSSQL (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.5.4 ACF Funcional Movimentos Geracao MSSQL (Parte4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.6.1 ACF Funcional Relatorios MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.6.2 ACF Funcional Relatorios MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.6.3 ACF Funcional Relatorios MSSQL (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.6.4 ACF Funcional Relatorios MSSQL (Parte4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.6.5 ACF Funcional Relatorios MSSQL (Parte5)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.7.1 ACF Funcional Utilitarios MSSQL (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.7.2 ACF Funcional Utilitarios MSSQL (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.7.3 ACF Funcional Utilitarios MSSQL (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\1.7.4 ACF Funcional Utilitarios MSSQL (Parte4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.1.1 ACF Funcional Cadastros Firebird 2.1 - (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.1.2 ACF Funcional Cadastros Firebird 2.1 - (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.1.3 ACF Funcional Cadastros Firebird 2.1 - (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.2.1 ACF Funcional Mov. Entradas Firebird 2.1 - (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.2.2 ACF Funcional Mov. Entradas Firebird 2.1 - (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.2.3 ACF Funcional Mov. Entradas Firebird 2.1 - (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.3.1 ACF Funcional Mov. Sa_das Firebird 2.1 - (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.3.2 ACF Funcional Mov. Sa_das Firebird 2.1 - (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.3.3 ACF Funcional Mov. Sa_das Firebird 2.1 - (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.4.1 ACF Funcional Outros Movimentos Firebird 2.1 - (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.4.2 ACF Funcional Outros Movimentos Firebird 2.1 - (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.4.3 ACF Funcional Outros Movimentos Firebird 2.1 - (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.5.1 ACF Funcional Mov. Gera__o Firebird 2.1 - (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.5.2 ACF Funcional Mov. Gera__o Firebird 2.1 - (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.5.3 ACF Funcional Mov. Gera__o Firebird 2.1 - (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.5.4 ACF Funcional Mov. Gera__o Firebird 2.1 - (Parte4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.6.1 ACF Funcional Relat_rios Firebird 2.1 - (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.6.2 ACF Funcional Relat_rios Firebird 2.1 - (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.6.3 ACF Funcional Relat_rios Firebird 2.1 - (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.6.4 ACF Funcional Relat_rios Firebird 2.1 - (Parte4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.6.5 ACF Funcional Relat_rios Firebird 2.1 - (Parte5)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.7.1 ACF Funcional Utilit_rios Firebird 2.1 - (Parte1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.7.2 ACF Funcional Utilit_rios Firebird 2.1 - (Parte2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.7.3 ACF Funcional Utilit_rios Firebird 2.1 - (Parte3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscal\3.7.4 ACF Funcional Utilit_rios Firebird 2.1 - (Parte4)"\*) do rd /s /q "%%i"

Title FISCAL XE6
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\1 ACF Unitarios Firebird 2.1"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\1.1 ACF Unitarios MSSQL"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\0.1 ACF Unitarios Firebird 2.1 (Win 7)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\0.2 ACF Unitarios MSSQL (Win 7)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\7.5 ACF Funcional Relat_rios FB 2.1 (Parte 5)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\7.4 ACF Funcional Relat_rios FB 2.1 (Parte 4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\7.3 ACF Funcional Relat_rios FB 2.1 (Parte 3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\7.2 ACF Funcional Relat_rios FB 2.1 (Parte 2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\7.1 ACF Funcional Relat_rios FB 2.1 (Parte 1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\5.2 - ACF Funcional Outros Movimentos Firebird 2.1 (Parte 2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\5.3 - ACF Funcional Outros Movimentos Firebird 2.1 (Parte 3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\5.1 - ACF Funcional Outros Movimentos Firebird 2.1 (Parte 1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\6.1 ACF Funcional Movimentos Geracao Firebird 2.1 (Parte 1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\6.2 ACF Funcional Movimentos Geracao Firebird 2.1 (Parte 2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\6.3 ACF Funcional Movimentos Geracao Firebird 2.1 (Parte 3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\6.4 ACF Funcional Movimentos Geracao - Importa__es FB 2.1 (Parte 4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\8.4 ACF Funcional Utilit_rios FB 2.1 (Parte 4)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\8.3 ACF Funcional Utilit_rios FB 2.1 (Parte 3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\8.2 ACF Funcional Utilit_rios FB 2.1 (Parte 2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\8.1 ACF Funcional Utilit_rios FB 2.1 (Parte 1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\2.3 -  ACF Funcional Cadastros Firebird 2.1 (Parte 3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\2.2 -  ACF Funcional Cadastros Firebird 2.1 (Parte 2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\2.1 -  ACF Funcional Cadastros Firebird 2.1 (Parte 1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\4.3 - ACF Funcional Mov. Sa_das Firebird 2.1 (Parte 3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\4.2 - ACF Funcional Mov. Sa_das Firebird 2.1 (Parte 2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\4.1 - ACF Funcional Mov. Sa_das Firebird 2.1 (Parte 1)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\3.3 - ACF Funcional Mov. Entradas Firebird 2.1 (Parte 3)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\3.2 - ACF Funcional Mov. Entradas Firebird 2.1 (Parte 2)"\*) do rd /s /q "%%i"
for /d %%i in ("C:\ProgramData\JetBrains\TeamCity\system\artifacts\TestesAcFiscalXe6\3.1 - ACF Funcional Mov. Entradas Firebird 2.1 (Parte 1)"\*) do rd /s /q "%%i"